language: android
jdk: oraclejdk8

env:
  # global variables
  global:
  - ANDROID_API_LEVEL=28
  - ANDROID_BUILD_TOOLS_VERSION=28.0.3
  - EMULATOR_API_LEVEL=25
  - ANDROID_ABI=armeabi-v7a

android:
  components:
  - tools
  - platform-tools
  # The SDK version used to compile your project
  - android-$ANDROID_API_LEVEL
  # The BuildTools version used by your project
  - build-tools-$ANDROID_BUILD_TOOLS_VERSION
  # Emulator config: system image
  #- sys-img-${ANDROID_ABI}-android-${ANDROID_API_LEVEL}

before_install:
  # Accept all sdk licenses
  yes | sdkmanager "platforms;android-${ANDROID_API_LEVEL}"


  # Install the rest of tools (e.g., avdmanager)
  - sdkmanager tools
  # Install the system image
  - sdkmanager "system-images;android-18;default;armeabi-v7a"
  # Create and start emulator for the script. Meant to race the install task.
  - echo no | avdmanager create avd --force -n test -k "system-images;android-25;default;armeabi-v7a"
  - $ANDROID_HOME/emulator/emulator -avd test -no-audio -no-window &

before_script:
  # Emulator Management: Create, Start
  #- echo no | android create avd --force -n test -t "android-"$EMULATOR_API_LEVEL --abi $ANDROID_ABI -c 100M
  #- emulator -avd test -no-audio -no-window &
  # wait for emulator
  - android-wait-for-emulator

script:
  # list the target ids
  - android list target
  # Run assemble and unit tests
  - ./gradlew clean assembleDebug assembleRelease connectedCheck