language: android
android:
  components:
  # The SDK version used to compile your project
  - android-28
  # The BuildTools version used by your project
  - build-tools-28.0.3
  # system image
  - sys-img-armeabi-v7a-android-28

before_install:
  # Accept all sdk licenses
  yes | sdkmanager "platforms;android-28"

before_script:
  # wait for emulator
  - android-wait-for-emulator

# Run assemble and unit tests
script:
  - ./gradlew clean assembleDebug assembleRelease connectedAndroidTest